### ISSUE TITLE
I tried creating s3 resource but got the error which is listed in the description

### ISSUE THREAD

**Issue by Harsh22222** [nealdct/python-for-aws-code#1]
Traceback (most recent call last):
  File "/home/ec2-user/environment/aws_services_py/s3_crud.py", line 14, in <module>
    s3.create_bucket(Bucket=bucket_name)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/boto3/resources/factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

**Comment by Harsh22222** [comment]
I added the following snippet:
`    s3.create_bucket(Bucket=bucket_name,CreateBucketConfiguration={
        'LocationConstraint':'ap-south-1'})`
and it worked... but while debugging and from the boto3 doc I inferred that if no region information is specified it takes up US East (N. Virginia) Region (us-east-1) by default.

What could be a potential reason for it?
